name: Meta Photo APP Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3
      # Set up Node.js (adjust the version as needed)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm
      # Install dependencies using pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      # Build the project (adjust the build command if necessary)
      - name: Build Project
        run: pnpm run build
      # Deploy to Vercel using the Vercel Action
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          prod: true
